name: project-test
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Test code coverage
        run: |
          make test-coverage
      - name: format code coverage
        uses: ./.github/actions/cc-test-reporter
        with:
          subcommand: "format-coverage -t lcov ./coverage/lcov.info"
      - name: upload code coverage
        uses: ./.github/actions/cc-test-reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          subcommand: "upload-coverage"

