name: project-test
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Test code coverage
        run: |
          make test-coverage
      - name: CodeClimate Code Coverage Test Reporter
        # You may pin to the exact commit or the version.
        # uses: xylabs/action-code-climate-test-reporter@79e542e6c82c5c48a50e885860eeed998467bbe5
        uses: xylabs/action-code-climate-test-reporter@v1.0.0
        with:
          # The cc-test-report subcommand (with flags/arguments) to execute
          subcommand: # default is help
