name: tests

on: push
jobs:
  start_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.x
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Linter test
        run: |
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: 6e1833aa96a15ec950d73c4462aec91a8cbf2ab38d40fa7460c4061b647870b5
        with:
          coverageCommand: make test-coverage
          debug: true
